name: Deploy All 5Pointers Services

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_backend:
        description: 'Deploy Backend'
        required: false
        default: 'true'
        type: boolean
      deploy_editor:
        description: 'Deploy Editor'
        required: false
        default: 'true'
        type: boolean
      deploy_subdomain:
        description: 'Deploy Subdomain Renderer'
        required: false
        default: 'true'
        type: boolean
      deploy_websocket:
        description: 'Deploy WebSocket'
        required: false
        default: 'true'
        type: boolean

jobs:
  deploy-backend:
    if: github.event.inputs.deploy_backend != 'false'
    uses: ./.github/workflows/5pointers-backend-deploy.yml
    secrets: inherit

  deploy-editor:
    if: github.event.inputs.deploy_editor != 'false'
    needs: deploy-backend
    uses: ./.github/workflows/5pointers-editor-deploy.yml
    secrets: inherit

  deploy-subdomain:
    if: github.event.inputs.deploy_subdomain != 'false'
    needs: deploy-backend
    uses: ./.github/workflows/5pointers-subdomain-deploy.yml
    secrets: inherit

  deploy-websocket:
    if: github.event.inputs.deploy_websocket != 'false'
    uses: ./.github/workflows/5pointers-websocket-deploy.yml
    secrets: inherit

  notify-completion:
    needs: [deploy-backend, deploy-editor, deploy-subdomain, deploy-websocket]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Deployment Summary
      run: |
        echo "🚀 5Pointers Deployment Summary:"
        echo "Backend: ${{ needs.deploy-backend.result }}"
        echo "Editor: ${{ needs.deploy-editor.result }}"
        echo "Subdomain Renderer: ${{ needs.deploy-subdomain.result }}"
        echo "WebSocket: ${{ needs.deploy-websocket.result }}"
        
        if [[ "${{ needs.deploy-backend.result }}" == "success" && 
              "${{ needs.deploy-editor.result }}" == "success" && 
              "${{ needs.deploy-subdomain.result }}" == "success" && 
              "${{ needs.deploy-websocket.result }}" == "success" ]]; then
          echo "✅ All 5Pointers services deployed successfully!"
        else
          echo "❌ Some deployments failed. Please check the logs."
        fi
