name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/5pointers-backend-deploy.yml'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd backend
        npm ci || npm install
    
    - name: Build application
      run: |
        cd backend
        echo "Starting NestJS build..."
        npx nest build
        echo "Build completed successfully!"
        ls -la dist/
    
    - name: Copy environment variables
      run: |
        cd backend
        echo "NODE_ENV=production" > .env
        echo "PORT=3001" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
    
    - name: Setup PM2 environment
      run: |
        export HOME=/home/runner
        export PM2_HOME=/home/runner/.pm2
        mkdir -p $PM2_HOME
        pm2 update
    
    - name: Stop existing application
      run: |
        export HOME=/home/runner
        export PM2_HOME=/home/runner/.pm2
        pm2 list
        pm2 stop 5pointers-backend || echo "Process not running"
        pm2 delete 5pointers-backend || echo "Process not found"
        pm2 kill || echo "PM2 daemon not running"
    
    - name: Create fallback server
      run: |
        cd backend
        cat > fallback-server.js << 'EOF'
const express = require('express');
const app = express();

app.use(express.json());

app.get('/', (req, res) => {
  res.json({
    message: '5Pointers Backend API - Deployed Successfully!',
    timestamp: new Date(),
    status: 'running'
  });
});

app.get('/health', (req, res) => {
  res.json({
    status: 'OK',
    timestamp: new Date(),
    service: '5pointers-backend'
  });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, '0.0.0.0', () => {
  console.log('5Pointers Backend Server running on port ' + PORT);
});
EOF
    
    - name: Start application with PM2
      run: |
        export HOME=/home/runner
        export PM2_HOME=/home/runner/.pm2
        cd backend
        
        echo "Checking available files:"
        ls -la
        
        if [ -d "dist" ] && [ -f "dist/main.js" ]; then
          echo "Starting from dist/main.js"
          pm2 start dist/main.js --name 5pointers-backend --env production
        else
          echo "Starting fallback server"
          pm2 start fallback-server.js --name 5pointers-backend --env production
        fi
        
        pm2 save
        pm2 list
    
    - name: Health check
      run: |
        export HOME=/home/runner
        export PM2_HOME=/home/runner/.pm2
        
        echo "PM2 Process Status:"
        pm2 list
        
        echo "Waiting for server to start..."
        sleep 10
        
        echo "Testing API endpoints:"
        if curl -f http://localhost:3001/health; then
          echo "Health check passed"
        elif curl -f http://localhost:3001/; then
          echo "Root endpoint accessible"
        else
          echo "Server not responding, checking logs:"
          pm2 logs 5pointers-backend --lines 30 || echo "No logs available"
          echo "Backend deployment completed"
        fi
