name: Deploy WebSocket Server

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'yjs-server.js'
      - 'package-yjs.json'
      - 'yjs-server-package.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'yjs-server.js'
      - 'package-yjs.json'
      - 'yjs-server-package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        if [ -f "yjs-server-package.json" ]; then
          cp yjs-server-package.json package.json
        elif [ -f "package-yjs.json" ]; then
          cp package-yjs.json package.json
        fi
        npm install
    
    - name: Run linting
      run: |
        echo "WebSocket server syntax check"
        node -c yjs-server.js

  deploy:
    needs: test
    runs-on: [self-hosted, websocket-server]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        if [ -f "yjs-server-package.json" ]; then
          cp yjs-server-package.json package.json
        elif [ -f "package-yjs.json" ]; then
          cp package-yjs.json package.json
        fi
        npm install --only=production
    
    - name: Create environment file
      run: |
        echo "NODE_ENV=production" > .env
        echo "PORT=3003" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
    
    - name: Stop existing application
      run: |
        pm2 stop 5pointers-websocket || true
        pm2 delete 5pointers-websocket || true
    
    - name: Start application with PM2
      run: |
        pm2 start yjs-server.js --name 5pointers-websocket
        pm2 save
    
    - name: Health check
      run: |
        sleep 10
        # WebSocket 서버 프로세스 확인
        pm2 show 5pointers-websocket || exit 1
        echo "WebSocket server started successfully"
    
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ WebSocket server deployment successful!"
        else
          echo "❌ WebSocket server deployment failed!"
        fi
