name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    branches: [ main ]
    paths: 
      - 'my-web-builder/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'my-web-builder/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: my-web-builder/apps/frontend/package-lock.json
        
    - name: Install root dependencies
      run: |
        cd my-web-builder
        npm install
        
    - name: Install frontend dependencies
      run: |
        cd my-web-builder/apps/frontend
        npm install
        
    - name: Create production environment file
      run: |
        cd my-web-builder/apps/frontend
        echo "VITE_API_URL=http://Jungle-backend-prod-env.eba-ftfwcygq.ap-northeast-2.elasticbeanstalk.com" > .env.production
        echo "VITE_WEBSOCKET_URL=wss://h0xs6j2ig6.execute-api.ap-northeast-2.amazonaws.com" >> .env.production
        echo "VITE_SUBDOMAIN_URL=http://1.238.129.195:3001" >> .env.production
        
    - name: Build application for production
      run: |
        cd my-web-builder/apps/frontend
        npm run build:production
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-northeast-2
        
    - name: Deploy to S3
      run: |
        cd my-web-builder/apps/frontend
        aws s3 sync dist/ s3://jungle-frontend-5 --delete
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E1YH7W2565N4LY \
          --paths "/*"
