name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "🚀 Starting deployment..."
          
          # 프로젝트 디렉토리로 이동
          cd /home/ubuntu/5_pointers
          
          # 최신 코드 가져오기
          echo "📥 Pulling latest code..."
          git pull origin main
          
          # 모노레포 의존성 설치
          echo "📦 Installing dependencies..."
          cd my-web-builder
          npm install -g pnpm
          pnpm install
          
          # Backend 환경변수 설정
          echo "🔧 Setting up backend environment..."
          cd /home/ubuntu/5_pointers/backend
          echo "NODE_ENV=production
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          DB_HOST=localhost
          DB_PORT=3306
          DB_USERNAME=root
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=jungle" > .env
          
          # PM2 프로세스 재시작
          echo "🔄 Restarting services..."
          pm2 restart all || {
            echo "Starting new PM2 processes..."
            
            # Backend 시작
            cd /home/ubuntu/5_pointers/backend
            pm2 start npm --name backend -- run start:dev
            
            # Turbo 모노레포 시작
            cd /home/ubuntu/5_pointers/my-web-builder
            pm2 start "pnpm run dev" --name "turbo-dev"
          }
          
          # PM2 설정 저장
          pm2 save
          
          echo "✅ Deployment completed successfully!"
          
          # 서비스 상태 확인
          echo "📊 Service status:"
          pm2 status