name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Build application
        run: |
          cd backend
          npm run build

      - name: Create .env file
        run: |
          cd backend
          echo "NODE_ENV=production" > .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_CALLBACK_URL=https://pagecube.net/social-callback?provider=google" >> .env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_REST_API_KEY }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
          echo "KAKAO_CALLBACK_URL=https://pagecube.net/social-callback?provider=kakao" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> .env
          echo "AWS_S3_BUCKET_NAME=5pointers-imagebucket" >> .env
          echo "AWS_REGION=ap-northeast-2" >> .env

      - name: Create deployment package
        run: |
          cd backend
          zip -r ../backend-deployment.zip . -x "node_modules/*" "*.git*" "test/*" "coverage/*" "*.log"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp backend-deployment.zip s3://elasticbeanstalk-ap-northeast-2-490004614784/backend-deployment-${{ github.sha }}.zip

      - name: Create application version
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          RANDOM_ID=$(openssl rand -hex 4)
          VERSION_LABEL="v1.0-${TIMESTAMP}-${RANDOM_ID}"
          echo "VERSION_LABEL=${VERSION_LABEL}" >> $GITHUB_ENV
          
          # 기존 버전이 있다면 삭제 시도 (실패해도 계속 진행)
          aws elasticbeanstalk delete-application-version \
            --application-name jungle-backend-prod \
            --version-label v1.0-${{ github.sha }} \
            --delete-source-bundle || true
          
          aws elasticbeanstalk create-application-version \
            --application-name jungle-backend-prod \
            --version-label ${VERSION_LABEL} \
            --description "Deployment from GitHub Actions - ${{ github.sha }} at ${TIMESTAMP}" \
            --source-bundle S3Bucket=elasticbeanstalk-ap-northeast-2-490004614784,S3Key=backend-deployment-${{ github.sha }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Jungle-backend-prod-env \
            --version-label ${{ env.VERSION_LABEL }}

      - name: Wait for deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --environment-name Jungle-backend-prod-env

      - name: Get deployment status
        run: |
          aws elasticbeanstalk describe-environments \
            --environment-names Jungle-backend-prod-env \
            --query 'Environments[0].{Status:Status,Health:Health,VersionLabel:VersionLabel}'
