name: Deploy Next.js App to EC2

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'my-web-builder/apps/subdomain-nextjs/**'
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd my-web-builder/apps/subdomain-nextjs
          npm install

      - name: Create production environment file
        run: |
          cd my-web-builder/apps/subdomain-nextjs
          rm -f .env.production
          echo "NEXT_PUBLIC_API_URL=https://ddukddak.org/api" > .env.production
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "NEXT_PUBLIC_KAKAO_CLIENT_ID=${{ secrets.KAKAO_JAVASCRIPT_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_KAKAO_JS_KEY=${{ secrets.KAKAO_JS_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_FRONTEND_URL=https://ddukddak.org" >> .env.production
          echo "Created .env.production:"
          cat .env.production

      - name: Build application
        run: |
          cd my-web-builder/apps/subdomain-nextjs
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2
        run: |
          # EC2 인스턴스에 배포
          aws s3 cp -r my-web-builder/apps/subdomain-nextjs/.next s3://jungle-frontend-5/nextjs-deployment/
          
          # EC2 인스턴스에서 배포 스크립트 실행
          aws ssm send-command \
            --instance-ids "i-0123456789abcdef0" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ubuntu/jungle/my-web-builder/apps/subdomain-nextjs",
              "aws s3 sync s3://jungle-frontend-5/nextjs-deployment/ .next/",
              "npm install --production",
              "pm2 restart subdomain-nextjs || pm2 start npm --name subdomain-nextjs -- start"
            ]'

      - name: Health check
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          
          # 헬스 체크
          curl -f http://3.35.141.231:3001 || {
            echo "❌ Deployment failed - health check failed"
            exit 1
          }
          
          echo "✅ Deployment successful!" 