name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    branches: [ main ]
    paths: 
      - 'my-web-builder/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'my-web-builder/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: my-web-builder/package-lock.json
        
    - name: Install dependencies
      run: |
        cd my-web-builder
        npm ci
        
    - name: Build application
      run: |
        cd my-web-builder
        npm run build
      env:
        VITE_API_URL: http://Jungle-backend-prod-env.eba-ftfwcygq.ap-northeast-2.elasticbeanstalk.com
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-northeast-2
        
    - name: Deploy to S3
      run: |
        cd my-web-builder
        aws s3 sync dist/ s3://jungle-frontend-5 --delete
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E1YH7W2565N4LY \
          --paths "/*"
